import { Injectable, NotFoundException, Logger } from '@nestjs/common';
import { PrismaService } from '../../../prisma';
import { NarrationGenerator } from './narration-generator';
import { UpsertNarrationDto } from './dto/upsert-narration.dto';
import { GenerateNarrationDto } from './dto/generate-narration.dto';
import { GenerateTtsDto } from './dto/generate-tts.dto';
import { NarrationType } from '@prisma/client';
import { MsEdgeTTS, OUTPUT_FORMAT } from 'msedge-tts';
import { join } from 'node:path';
import { existsSync, mkdirSync, statSync } from 'node:fs';
import { randomUUID } from 'node:crypto';

const VOICE_MAP: Record<string, string> = {
  VI: 'vi-VN-HoaiMyNeural',
  EN: 'en-US-AriaNeural',
};

const NARRATIONS_UPLOAD_DIR = join(process.cwd(), 'uploads', 'narrations');

@Injectable()
export class NarrationService {
  private readonly logger = new Logger(NarrationService.name);

  constructor(
    private readonly prisma: PrismaService,
    private readonly generator: NarrationGenerator,
  ) {
    if (!existsSync(NARRATIONS_UPLOAD_DIR)) {
      mkdirSync(NARRATIONS_UPLOAD_DIR, { recursive: true });
    }
  }

  // ─────────────────────────────────────────────
  // CRUD
  // ─────────────────────────────────────────────

  async getTourNarrations(tourId: string) {
    await this.ensureTourExists(tourId);
    return this.prisma.tourNarration.findMany({
      where: { tourId },
      orderBy: { orderIndex: 'asc' },
    });
  }

  async upsertNarrations(tourId: string, dto: UpsertNarrationDto) {
    await this.ensureTourExists(tourId);

    const results = [];
    for (const item of dto.narrations) {
      const saved = await this.prisma.tourNarration.upsert({
        where: {
          tourId_type_orderIndex: {
            tourId,
            type: item.type,
            orderIndex: item.orderIndex,
          },
        },
        update: {
          fromPoiId: item.fromPoiId ?? null,
          toPoiId: item.toPoiId ?? null,
          scriptVi: item.scriptVi ?? null,
          scriptEn: item.scriptEn ?? null,
          isAutoGenerated: false,
        },
        create: {
          tourId,
          type: item.type,
          orderIndex: item.orderIndex,
          fromPoiId: item.fromPoiId ?? null,
          toPoiId: item.toPoiId ?? null,
          scriptVi: item.scriptVi ?? null,
          scriptEn: item.scriptEn ?? null,
          isAutoGenerated: false,
        },
      });
      results.push(saved);
    }
    return results;
  }

  async deleteNarration(tourId: string, id: string) {
    await this.ensureTourExists(tourId);
    const narration = await this.prisma.tourNarration.findFirst({
      where: { id, tourId },
    });
    if (!narration) throw new NotFoundException('Narration not found');
    return this.prisma.tourNarration.delete({ where: { id } });
  }

  // ─────────────────────────────────────────────
  // Phase 3: Auto-generate Scripts
  // ─────────────────────────────────────────────

  async generateScripts(tourId: string, dto: GenerateNarrationDto) {
    const tour = await this.prisma.tour.findFirst({
      where: { id: tourId, deletedAt: null },
      include: {
        tourPois: {
          include: { poi: true },
          orderBy: { orderIndex: 'asc' },
        },
      },
    });
    if (!tour) throw new NotFoundException('Tour not found');

    const typesToGenerate = dto.types ?? Object.values(NarrationType);
    const overwrite = dto.overwriteExisting ?? false;

    // Build context
    const pois = tour.tourPois;
    const totalDistance = this.calculateTotalDistance(pois);
    const estimatedDuration = tour.estimatedDuration ?? Math.round(totalDistance / 75 + pois.length * 10);
    const categoryBreakdown: Record<string, number> = {};
    for (const tp of pois) {
      categoryBreakdown[tp.poi.category] = (categoryBreakdown[tp.poi.category] || 0) + 1;
    }

    const ctx = {
      tourName: tour.nameVi,
      tourDescription: tour.descriptionVi,
      totalDistance,
      estimatedDuration,
      poiCount: pois.length,
      categoryBreakdown,
      pois: pois.map((tp, i) => {
        const prevPoi = i > 0 ? pois[i - 1] : null;
        const dist = prevPoi
          ? this.haversineMeters(
              prevPoi.poi.latitude, prevPoi.poi.longitude,
              tp.poi.latitude, tp.poi.longitude,
            )
          : 0;
        return {
          id: tp.poiId,
          name: tp.poi.nameVi,
          category: tp.poi.category as string,
          description: tp.poi.descriptionVi,
          distanceFromPrev: Math.round(dist),
          walkTimeFromPrev: Math.round(dist / 75),
          orderIndex: tp.orderIndex,
        };
      }),
    };

    // Build narration scripts list
    type NarrationPayload = {
      type: NarrationType;
      orderIndex: number;
      fromPoiId: string | null;
      toPoiId: string | null;
      scriptVi: string;
      scriptEn: string;
      isAutoGenerated: boolean;
    };

    const scripts: NarrationPayload[] = [];
    let orderIndex = 0;

    // INTRO
    if (typesToGenerate.includes(NarrationType.INTRO)) {
      scripts.push({
        type: NarrationType.INTRO,
        orderIndex: orderIndex++,
        fromPoiId: null,
        toPoiId: pois[0]?.poiId ?? null,
        scriptVi: this.generator.generateIntro(ctx, 'VI'),
        scriptEn: this.generator.generateIntro(ctx, 'EN'),
        isAutoGenerated: true,
      });
    }

    // TRANSITION → POI[0] (from start)
    for (let i = 0; i < pois.length; i++) {
      const poi = pois[i];
      const prevPoi = i > 0 ? pois[i - 1] : null;
      const distM = ctx.pois[i].distanceFromPrev;
      const walkMin = ctx.pois[i].walkTimeFromPrev;

      if (typesToGenerate.includes(NarrationType.TRANSITION)) {
        scripts.push({
          type: NarrationType.TRANSITION,
          orderIndex: orderIndex++,
          fromPoiId: prevPoi?.poiId ?? null,
          toPoiId: poi.poiId,
          scriptVi: this.generator.generateTransition(poi.poi.nameVi, distM, walkMin, poi.poi.category as string, poi.poi.descriptionVi, 'VI'),
          scriptEn: this.generator.generateTransition(poi.poi.nameEn ?? poi.poi.nameVi, distM, walkMin, poi.poi.category as string, poi.poi.descriptionEn ?? poi.poi.descriptionVi, 'EN'),
          isAutoGenerated: true,
        });
      }

      if (typesToGenerate.includes(NarrationType.ARRIVAL)) {
        scripts.push({
          type: NarrationType.ARRIVAL,
          orderIndex: orderIndex++,
          fromPoiId: prevPoi?.poiId ?? null,
          toPoiId: poi.poiId,
          scriptVi: this.generator.generateArrival(poi.poi.nameVi, i + 1, 'VI'),
          scriptEn: this.generator.generateArrival(poi.poi.nameEn ?? poi.poi.nameVi, i + 1, 'EN'),
          isAutoGenerated: true,
        });
      }
    }

    // OUTRO
    if (typesToGenerate.includes(NarrationType.OUTRO)) {
      scripts.push({
        type: NarrationType.OUTRO,
        orderIndex: orderIndex++,
        fromPoiId: pois[pois.length - 1]?.poiId ?? null,
        toPoiId: null,
        scriptVi: this.generator.generateOutro(ctx, 'VI'),
        scriptEn: this.generator.generateOutro(ctx, 'EN'),
        isAutoGenerated: true,
      });
    }

    // Upsert scripts to DB
    let generated = 0;
    let skipped = 0;

    for (const script of scripts) {
      const existing = await this.prisma.tourNarration.findFirst({
        where: { tourId, type: script.type, orderIndex: script.orderIndex },
      });

      if (existing && !overwrite && !existing.isAutoGenerated) {
        skipped++;
        continue;
      }

      await this.prisma.tourNarration.upsert({
        where: { tourId_type_orderIndex: { tourId, type: script.type, orderIndex: script.orderIndex } },
        create: { tourId, ...script },
        update: { ...script },
      });
      generated++;
    }

    return {
      generated,
      skipped,
      narrations: await this.prisma.tourNarration.findMany({
        where: { tourId },
        orderBy: { orderIndex: 'asc' },
      }),
    };
  }

  // ─────────────────────────────────────────────
  // Phase 4: TTS Audio Generation
  // ─────────────────────────────────────────────

  async generateTts(tourId: string, dto: GenerateTtsDto) {
    await this.ensureTourExists(tourId);

    const languages = (dto.languages ?? ['VI', 'EN']).map((l) => l.toUpperCase());

    const narrations = await this.prisma.tourNarration.findMany({
      where: {
        tourId,
        ...(dto.narrationIds?.length ? { id: { in: dto.narrationIds } } : {}),
      },
      orderBy: { orderIndex: 'asc' },
    });

    const tourDir = join(NARRATIONS_UPLOAD_DIR, tourId);
    if (!existsSync(tourDir)) {
      mkdirSync(tourDir, { recursive: true });
    }

    let generated = 0;
    const results = [];

    for (const narration of narrations) {
      const updateData: { audioViUrl?: string; audioEnUrl?: string } = {};

      for (const lang of languages) {
        const script = lang === 'VI' ? narration.scriptVi : narration.scriptEn;
        if (!script) continue;

        const voiceName = VOICE_MAP[lang];
        if (!voiceName) {
          this.logger.warn(`No voice mapping for language: ${lang}`);
          continue;
        }

        try {
          const audioUrl = await this.synthesizeAudio(script, voiceName, tourId, narration.type, narration.orderIndex, lang);

          if (lang === 'VI') updateData.audioViUrl = audioUrl;
          else updateData.audioEnUrl = audioUrl;

          generated++;
        } catch (err) {
          this.logger.error(`TTS failed for narration ${narration.id} [${lang}]: ${err.message}`);
        }
      }

      if (Object.keys(updateData).length > 0) {
        const updated = await this.prisma.tourNarration.update({
          where: { id: narration.id },
          data: updateData,
        });
        results.push(updated);
      }
    }

    return { generated, narrations: results };
  }

  async generateSingleTts(tourId: string, narrationId: string, dto: GenerateTtsDto) {
    return this.generateTts(tourId, { ...dto, narrationIds: [narrationId] });
  }

  // ─────────────────────────────────────────────
  // Public endpoint (Mobile)
  // ─────────────────────────────────────────────

  async getPublicNarrations(tourId: string) {
    return this.prisma.tourNarration.findMany({
      where: { tourId },
      orderBy: { orderIndex: 'asc' },
      select: {
        id: true,
        type: true,
        orderIndex: true,
        fromPoiId: true,
        toPoiId: true,
        scriptVi: true,
        scriptEn: true,
        audioViUrl: true,
        audioEnUrl: true,
      },
    });
  }

  // ─────────────────────────────────────────────
  // Helpers
  // ─────────────────────────────────────────────

  private async ensureTourExists(tourId: string) {
    const tour = await this.prisma.tour.findFirst({
      where: { id: tourId, deletedAt: null },
      select: { id: true },
    });
    if (!tour) throw new NotFoundException('Tour not found');
    return tour;
  }

  private async synthesizeAudio(
    script: string,
    voiceName: string,
    tourId: string,
    type: NarrationType,
    orderIndex: number,
    lang: string,
  ): Promise<string> {
    const tts = new MsEdgeTTS();
    await tts.setMetadata(voiceName, OUTPUT_FORMAT.AUDIO_24KHZ_96KBITRATE_MONO_MP3);

    const fileId = randomUUID();
    const fileName = `${type.toLowerCase()}_${String(orderIndex).padStart(2, '0')}_${lang.toLowerCase()}_${fileId}`;
    const outputDir = join(NARRATIONS_UPLOAD_DIR, tourId, fileName);

    if (!existsSync(outputDir)) {
      mkdirSync(outputDir, { recursive: true });
    }

    const { audioFilePath } = await tts.toFile(outputDir, script);
    tts.close();

    this.logger.log(`TTS narration generated: ${audioFilePath}`);

    const relativePath = audioFilePath
      .replace(process.cwd(), '')
      .replaceAll('\\', '/');

    return relativePath;
  }

  private haversineMeters(lat1: number, lon1: number, lat2: number, lon2: number): number {
    const R = 6371000;
    const dLat = ((lat2 - lat1) * Math.PI) / 180;
    const dLon = ((lon2 - lon1) * Math.PI) / 180;
    const a =
      Math.sin(dLat / 2) ** 2 +
      Math.cos((lat1 * Math.PI) / 180) *
        Math.cos((lat2 * Math.PI) / 180) *
        Math.sin(dLon / 2) ** 2;
    return R * 2 * Math.atan2(Math.sqrt(a), Math.sqrt(1 - a));
  }

  private calculateTotalDistance(pois: Array<{ poi: { latitude: number; longitude: number } }>): number {
    let total = 0;
    for (let i = 1; i < pois.length; i++) {
      total += this.haversineMeters(
        pois[i - 1].poi.latitude, pois[i - 1].poi.longitude,
        pois[i].poi.latitude, pois[i].poi.longitude,
      );
    }
    return Math.round(total);
  }
}
