/**
 * Shared TypeScript definitions for localization across web and mobile
 * Compatible with React and React Native contexts
 */

// ============================================================================
// Core Domain Types
// ============================================================================

/**
 * Language code in BCP 47 format
 * Examples: 'en', 'vi', 'de', 'en-US', 'zh-Hant'
 */
export type BCP47Language = string & { readonly __brand: 'BCP47Language' };

/**
 * Create a branded BCP47Language type
 */
export const createBCP47Language = (code: string): BCP47Language => {
  return code as BCP47Language;
};

/**
 * Supported language configuration
 */
export interface SupportedLanguage {
  /** Language code in BCP 47 format */
  code: BCP47Language;
  /** Display label (e.g., 'English', 'Vietnamese') */
  label: string;
  /** Optional flag emoji or icon identifier */
  flag?: string;
  /** Whether this language is currently enabled */
  enabled: boolean;
  /** Whether text localization is supported */
  supportsText: boolean;
  /** Whether text-to-speech is supported */
  supportsTts: boolean;
  /** Priority order for display (lower number = higher priority) */
  priority: number;
  /** Whether shop owners can edit this language */
  shopOwnerEditable: boolean;
  /** Default TTS voice for this language */
  defaultVoice?: string;
  /** Last update timestamp (ISO 8601) */
  updatedAt: string;
}

/**
 * POI localization data
 */
export interface PoiLocalization {
  /** Language code */
  language: BCP47Language;
  /** Localized name */
  name: string;
  /** Localized description */
  description: string;
  /** Source language if auto-generated from another language */
  sourceLanguage?: BCP47Language;
  /** Whether this localization was auto-generated */
  autoGenerated: boolean;
  /** Last update timestamp (ISO 8601) */
  updatedAt: string;
  /** User ID or system identifier of who updated this */
  updatedBy: string;
}

/**
 * Response envelope for listing POI localizations
 */
export interface ListLocalizationsResponse {
  /** POI identifier */
  poiId: string;
  /** Metadata about the response */
  meta: {
    /** Last synchronization timestamp (ISO 8601) */
    lastSyncedAt: string;
  };
  /** Array of localization items */
  items: PoiLocalization[];
}

/**
 * Request envelope for saving POI localizations
 */
export interface SaveLocalizationsRequest {
  /** Last synchronization timestamp for optimistic concurrency control */
  lastSyncedAt: string;
  /** Force save even if conflicts exist */
  force?: boolean;
  /** Localization items to save */
  items: PoiLocalization[];
}

/**
 * Response envelope for saving POI localizations
 */
export interface SaveLocalizationsResponse {
  /** POI identifier */
  poiId: string;
  /** Metadata about the response */
  meta: {
    /** New last synchronization timestamp (ISO 8601) */
    lastSyncedAt: string;
  };
}

// ============================================================================
// Request/Response DTOs
// ============================================================================

/**
 * Request to generate localization (text or audio)
 */
export interface LocalizationRequest {
  /** POI identifier */
  poiId: string;
  /** Target language for localization */
  targetLanguage: BCP47Language;
  /** Type of localization requested */
  type: 'text' | 'audio' | 'both';
  /** Optional context for generation */
  context?: {
    sourceLanguage?: BCP47Language;
    tone?: string;
    maxLength?: number;
  };
}

/**
 * Response from localization request
 */
export interface LocalizationRequestResponse {
  /** Unique request identifier */
  requestId: string;
  /** Current status of the request */
  status: 'pending' | 'processing' | 'completed' | 'failed';
  /** Optional error message */
  error?: string;
  /** Optional generated localization data */
  data?: PoiLocalization;
}

// ============================================================================
// Analytics Event Types
// ============================================================================

/**
 * Localization action event for analytics
 */
export interface LocalizationActionEvent {
  /** POI identifier */
  poiId: string;
  /** Language affected */
  language: BCP47Language;
  /** Action performed */
  action: 'save' | 'delete' | 'request' | 'generate_audio';
  /** Role performing the action */
  role: 'admin' | 'shopOwner' | 'mobile';
  /** Operation latency in milliseconds */
  latencyMs: number;
  /** Whether the action succeeded */
  success: boolean;
  /** Optional error code if unsuccessful */
  errorCode?: string;
  /** Timestamp (ISO 8601) */
  timestamp?: string;
}

/**
 * Localization dropdown view event for analytics
 */
export interface LocalizationDropdownViewEvent {
  /** POI identifier */
  poiId: string;
  /** Number of languages displayed when dropdown opened */
  openedLanguagesCount: number;
  /** Role of the user viewing */
  role: 'admin' | 'shopOwner' | 'mobile';
  /** Duration the dropdown was open in milliseconds */
  durationMs: number;
  /** Timestamp (ISO 8601) */
  timestamp?: string;
}

/**
 * Mobile language switch event for analytics
 */
export interface MobileLanguageSwitchEvent {
  /** POI identifier */
  poiId: string;
  /** Language switched from */
  fromLanguage: BCP47Language;
  /** Language switched to */
  toLanguage: BCP47Language;
  /** Whether the localization was served from cache */
  cacheHit: boolean;
  /** Whether the localization was served from memory */
  memoryHit: boolean;
  /** Whether the app was in offline mode */
  offline: boolean;
  /** Timestamp (ISO 8601) */
  timestamp?: string;
}

/**
 * Localization cache eviction event for analytics
 */
export interface LocalizationCacheEvictionEvent {
  /** POI identifier that was evicted */
  evictedPoiId: string;
  /** Last time this POI was viewed (ISO 8601) */
  lastViewedAt: string;
  /** Reason for eviction */
  reason: 'lru' | 'ttl';
  /** Timestamp of eviction (ISO 8601) */
  timestamp?: string;
}

// ============================================================================
// Hook State Types
// ============================================================================

/**
 * State for the usePoiLocalizations hook
 */
export interface UsePoiLocalizationsState {
  /** Current localization items */
  items: PoiLocalization[];
  /** Draft changes by language (not yet saved) */
  draftByLanguage: Record<string, PoiLocalization>;
  /** Dirty flag for each language (has unsaved changes) */
  dirtyMap: Record<string, boolean>;
  /** Current pending mutation operation */
  pendingMutation: {
    type: 'save' | 'delete' | 'generate';
    language: BCP47Language;
    startedAt: string;
  } | null;
  /** Errors by language */
  errors: Record<string, string>;
  /** Last synchronization timestamp from server */
  lastSyncedAt?: string;
  /** Last fetch timestamp from server */
  lastFetchedAt?: string;
}

/**
 * Configuration for localization client
 */
export interface LocalizationClientConfig {
  /** Base URL for localization API */
  baseUrl: string;
  /** Authentication mode */
  authMode: 'bearer' | 'session' | 'public';
  /** Bearer token (if authMode is 'bearer') */
  token?: string;
  /** Optional capabilities/features to enable */
  capabilities?: {
    enableCache?: boolean;
    enableOfflineSync?: boolean;
    enableAnalytics?: boolean;
    cacheMaxSize?: number;
    cacheTtlMs?: number;
  };
}

// ============================================================================
// Type Guards
// ============================================================================

/**
 * Check if a value is a valid BCP47Language
 */
export const isBCP47Language = (value: unknown): value is BCP47Language => {
  if (typeof value !== 'string') return false;
  // Simple BCP 47 validation: language tag format
  return /^[a-z]{2,3}(-[a-z]{2})?(-[a-z]{4})?(-[a-z]{2})?(-[x-][a-z0-9]+)*$/i.test(
    value
  );
};

/**
 * Check if a value is a SupportedLanguage
 */
export const isSupportedLanguage = (
  value: unknown
): value is SupportedLanguage => {
  if (typeof value !== 'object' || value === null) return false;
  const obj = value as Record<string, unknown>;
  return (
    typeof obj.code === 'string' &&
    typeof obj.label === 'string' &&
    typeof obj.enabled === 'boolean' &&
    typeof obj.supportsText === 'boolean' &&
    typeof obj.supportsTts === 'boolean' &&
    typeof obj.priority === 'number' &&
    typeof obj.shopOwnerEditable === 'boolean' &&
    typeof obj.updatedAt === 'string'
  );
};

/**
 * Check if a value is a PoiLocalization
 */
export const isPoiLocalization = (
  value: unknown
): value is PoiLocalization => {
  if (typeof value !== 'object' || value === null) return false;
  const obj = value as Record<string, unknown>;
  return (
    typeof obj.language === 'string' &&
    typeof obj.name === 'string' &&
    typeof obj.description === 'string' &&
    typeof obj.autoGenerated === 'boolean' &&
    typeof obj.updatedAt === 'string' &&
    typeof obj.updatedBy === 'string'
  );
};
