/**
 * Pure utility functions for localization validation, diff computation, and staleness checks
 * NO React dependencies - compatible with Node.js, browser, and React Native
 */

import { BCP47Language, PoiLocalization } from './types';

// ============================================================================
// Validation Functions
// ============================================================================

/**
 * Validate localization name
 * Rules: 3-80 characters, no double-spaces
 */
export function validateLocalizationName(name: string): {
  valid: boolean;
  error?: string;
} {
  if (name.length < 3) {
    return { valid: false, error: 'Name must be at least 3 characters' };
  }

  if (name.length > 80) {
    return { valid: false, error: 'Name must not exceed 80 characters' };
  }

  if (/  /.test(name)) {
    return { valid: false, error: 'Name must not contain double-spaces' };
  }

  return { valid: true };
}

/**
 * Validate localization description
 * Rules: 10-2000 characters
 */
export function validateLocalizationDescription(desc: string): {
  valid: boolean;
  error?: string;
} {
  if (desc.length < 10) {
    return {
      valid: false,
      error: 'Description must be at least 10 characters',
    };
  }

  if (desc.length > 2000) {
    return {
      valid: false,
      error: 'Description must not exceed 2000 characters',
    };
  }

  return { valid: true };
}

// ============================================================================
// Diff/Conflict Detection
// ============================================================================

/**
 * Represents a difference between local and remote localization
 */
export interface LocalizationDiff {
  /** Language code */
  language: BCP47Language;
  /** Field that differs */
  field: 'name' | 'description' | 'autoGenerated';
  /** Local value */
  local: string | boolean;
  /** Remote value */
  remote: string | boolean;
}

/**
 * Compute differences between local and remote localization versions
 * Returns array of all changed fields
 */
export function computeDiff(
  local: PoiLocalization,
  remote: PoiLocalization
): LocalizationDiff[] {
  const diffs: LocalizationDiff[] = [];

  // Check name field
  if (local.name !== remote.name) {
    diffs.push({
      language: local.language,
      field: 'name',
      local: local.name,
      remote: remote.name,
    });
  }

  // Check description field
  if (local.description !== remote.description) {
    diffs.push({
      language: local.language,
      field: 'description',
      local: local.description,
      remote: remote.description,
    });
  }

  // Check autoGenerated field
  if (local.autoGenerated !== remote.autoGenerated) {
    diffs.push({
      language: local.language,
      field: 'autoGenerated',
      local: local.autoGenerated,
      remote: remote.autoGenerated,
    });
  }

  return diffs;
}

// ============================================================================
// Staleness Check
// ============================================================================

/**
 * Check if lastSyncedAt exceeds threshold (milliseconds)
 * Compares current time against lastSyncedAt ISO 8601 timestamp
 *
 * @param lastSyncedAt ISO 8601 timestamp string
 * @param threshold Time threshold in milliseconds (default: 0 = any age is stale)
 * @returns true if data is stale, false otherwise
 */
export function isStaleLastSyncedAt(
  lastSyncedAt: string,
  threshold: number = 0
): boolean {
  try {
    const lastSyncedTime = new Date(lastSyncedAt).getTime();
    const currentTime = Date.now();
    const age = currentTime - lastSyncedTime;

    return age > threshold;
  } catch (error) {
    // Invalid date format - consider as stale
    return true;
  }
}
