import { describe, it, expect, vi, beforeEach } from 'vitest';
import axios from 'axios';
import { LocalizationClient } from '../client';
import type { SaveLocalizationsRequest } from '../types';

// Mock axios
vi.mock('axios');
const mockedAxios = vi.mocked(axios);

describe('LocalizationClient', () => {
  let client: LocalizationClient;

  beforeEach(() => {
    vi.clearAllMocks();

    // Mock axios.create to return a mock axios instance
    const mockAxiosInstance = {
      get: vi.fn(),
      put: vi.fn(),
      delete: vi.fn(),
      post: vi.fn(),
      defaults: { withCredentials: false },
    };

    mockedAxios.create.mockReturnValue(mockAxiosInstance as any);

    client = new LocalizationClient({
      baseUrl: 'http://localhost:3000/api',
      authMode: 'bearer',
      token: 'test-token',
    });
  });

  it('should list localizations with metadata', async () => {
    const mockResponse = {
      data: {
        poiId: 'poi-1',
        localizations: [
          {
            language: 'en-US' as const,
            name: 'Test',
            description: 'Test description',
            autoGenerated: false,
            lastModifiedAt: '2026-04-01T00:00:00Z',
          },
        ],
        lastSyncedAt: '2026-04-01T00:00:00Z',
      },
    };

    const mockAxiosInstance = mockedAxios.create.mock.results[0].value;
    (mockAxiosInstance.get as any).mockResolvedValue(mockResponse);

    const result = await client['listPoiLocalizations']('poi-1');

    expect(result).toEqual(mockResponse.data);
    expect(mockAxiosInstance.get).toHaveBeenCalledWith(
      '/pois/poi-1/localizations',
      expect.objectContaining({
        headers: expect.objectContaining({
          Authorization: 'Bearer test-token',
        }),
      })
    );
  });

  it('should include lastSyncedAt in save request', async () => {
    const saveRequest: SaveLocalizationsRequest = {
      poiId: 'poi-1',
      language: 'en-US' as const,
      name: 'Updated Name',
      description: 'Updated description',
      autoGenerated: false,
      lastSyncedAt: '2026-04-01T00:00:00Z',
    };

    const mockResponse = {
      data: {
        success: true,
        lastSyncedAt: '2026-04-01T10:00:00Z',
      },
    };

    const mockAxiosInstance = mockedAxios.create.mock.results[0].value;
    (mockAxiosInstance.put as any).mockResolvedValue(mockResponse);

    const result = await client['savePoiLocalizations']('poi-1', saveRequest);

    expect(result).toEqual(mockResponse.data);
    expect(mockAxiosInstance.put).toHaveBeenCalledWith(
      '/pois/poi-1/localizations',
      expect.objectContaining({
        lastSyncedAt: '2026-04-01T00:00:00Z',
      }),
      expect.objectContaining({
        headers: expect.objectContaining({
          Authorization: 'Bearer test-token',
        }),
      })
    );
  });

  it('should send correct endpoint for delete', async () => {
    const mockAxiosInstance = mockedAxios.create.mock.results[0].value;
    (mockAxiosInstance.delete as any).mockResolvedValue({});

    await client['deletePoiLocalization']('poi-1', 'en-US' as const);

    expect(mockAxiosInstance.delete).toHaveBeenCalledWith(
      '/pois/poi-1/localizations/en-US',
      expect.objectContaining({
        headers: expect.objectContaining({
          Authorization: 'Bearer test-token',
        }),
      })
    );
  });

  it('should propagate 409 conflict errors', async () => {
    const conflictError = new Error('Conflict');
    (conflictError as any).response = { status: 409 };

    const mockAxiosInstance = mockedAxios.create.mock.results[0].value;
    (mockAxiosInstance.put as any).mockRejectedValue(conflictError);

    const saveRequest: SaveLocalizationsRequest = {
      poiId: 'poi-1',
      language: 'en-US' as const,
      name: 'Updated',
      description: 'Updated description',
      autoGenerated: false,
      lastSyncedAt: '2026-04-01T00:00:00Z',
    };

    await expect(
      client['savePoiLocalizations']('poi-1', saveRequest)
    ).rejects.toThrow();
  });
});
