import { describe, it, expect, vi, beforeEach } from 'vitest';
import { renderHook, act } from '@testing-library/react';
import { usePoiLocalizations, UsePoiLocalizationsReturn } from '../usePoiLocalizations';
import * as client from '../client';
import type { ListLocalizationsResponse, BCP47Language, UsePoiLocalizationsOptions } from '../types';

// Mock the client module
vi.mock('../client', () => ({
  createLocalizationClient: vi.fn(),
  LocalizationClient: vi.fn(),
}));

// Mock React Query
vi.mock('@tanstack/react-query', () => ({
  useQuery: vi.fn((options) => ({
    data: {
      poiId: 'poi-1',
      localizations: [
        {
          language: 'en-US' as const,
          name: 'Test Name',
          description: 'Test description',
          autoGenerated: false,
          lastModifiedAt: '2026-04-01T00:00:00Z',
        },
      ],
      lastSyncedAt: '2026-04-01T00:00:00Z',
    },
    isLoading: false,
    error: null,
    isFetching: false,
  })),
  useMutation: vi.fn((options) => ({
    mutate: vi.fn(),
    mutateAsync: vi.fn((payload) => Promise.resolve(payload)),
    isPending: false,
    isError: false,
    error: null,
    data: null,
  })),
  useQueryClient: vi.fn(() => ({
    invalidateQueries: vi.fn(),
  })),
}));

describe('usePoiLocalizations', () => {
  const mockConfig: UsePoiLocalizationsOptions = {
    clientConfig: {
      baseUrl: 'http://localhost:3000/api',
      authMode: 'bearer',
      token: 'test-token',
    },
  };

  beforeEach(() => {
    vi.clearAllMocks();
    const mockClient = {
      listPoiLocalizations: vi.fn(),
      savePoiLocalizations: vi.fn(),
      deletePoiLocalization: vi.fn(),
    };
    vi.mocked(client.createLocalizationClient).mockReturnValue(mockClient as any);
  });

  it('should instantiate hook with config', () => {
    const { result } = renderHook(() => usePoiLocalizations('poi-1', mockConfig));

    expect(result.current).toBeDefined();
    expect(result.current.isLoading).toBe(false);
    expect(result.current.data).toBeDefined();
  });

  it('should update draft and mark dirty on editLanguage', () => {
    const { result } = renderHook(() => usePoiLocalizations('poi-1', mockConfig));

    act(() => {
      result.current.editLanguage('en-US' as BCP47Language, {
        name: 'Updated Name',
        description: 'Updated description',
        autoGenerated: false,
        language: 'en-US' as const,
        lastModifiedAt: '2026-04-01T00:00:00Z',
      });
    });

    expect(result.current.state.draftByLanguage['en-US']).toBeDefined();
    expect(result.current.state.dirtyMap['en-US']).toBe(true);
  });

  it('should clear dirty state on discardLanguage', () => {
    const { result } = renderHook(() => usePoiLocalizations('poi-1', mockConfig));

    // First mark as dirty
    act(() => {
      result.current.editLanguage('en-US' as BCP47Language, {
        name: 'Updated Name',
        description: 'Updated description',
        autoGenerated: false,
        language: 'en-US' as const,
        lastModifiedAt: '2026-04-01T00:00:00Z',
      });
    });

    expect(result.current.state.dirtyMap['en-US']).toBe(true);

    // Now discard
    act(() => {
      result.current.discardLanguage('en-US' as BCP47Language);
    });

    expect(result.current.state.dirtyMap['en-US']).toBeFalsy();
  });

  it('should fire dirty change callback when dirty count changes', () => {
    const onDirtyChange = vi.fn();
    const configWithCallback: UsePoiLocalizationsOptions = {
      ...mockConfig,
      onDirtyChange,
    };

    const { result } = renderHook(() =>
      usePoiLocalizations('poi-1', configWithCallback)
    );

    act(() => {
      result.current.editLanguage('en-US' as BCP47Language, {
        name: 'Updated Name',
        description: 'Updated description',
        autoGenerated: false,
        language: 'en-US' as const,
        lastModifiedAt: '2026-04-01T00:00:00Z',
      });
    });

    // Callback should be called when dirty count changes
    expect(onDirtyChange).toHaveBeenCalled();
  });
});
