import api from '../lib/api';

export type NarrationType = 'INTRO' | 'TRANSITION' | 'ARRIVAL' | 'OUTRO';

export interface TourNarration {
    id: string;
    tourId: string;
    type: NarrationType;
    orderIndex: number;
    fromPoiId: string | null;
    toPoiId: string | null;
    scriptVi: string | null;
    scriptEn: string | null;
    audioViUrl: string | null;
    audioEnUrl: string | null;
    isAutoGenerated: boolean;
    createdAt: string;
    updatedAt: string;
}

export interface UpsertNarrationPayload {
    narrations: Array<{
        type: NarrationType;
        orderIndex: number;
        fromPoiId?: string | null;
        toPoiId?: string | null;
        scriptVi?: string | null;
        scriptEn?: string | null;
    }>;
}

export interface GenerateNarrationOptions {
    types?: NarrationType[];
    overwriteExisting?: boolean;
}

export interface GenerateTtsOptions {
    languages?: string[];
    narrationIds?: string[];
}

export const narrationService = {
    getAll: async (tourId: string) => {
        const response = await api.get<TourNarration[]>(`/tours/${tourId}/narrations`);
        return response.data;
    },

    upsert: async (tourId: string, payload: UpsertNarrationPayload) => {
        const response = await api.put<TourNarration[]>(`/tours/${tourId}/narrations`, payload);
        return response.data;
    },

    delete: async (tourId: string, narrationId: string) => {
        const response = await api.delete(`/tours/${tourId}/narrations/${narrationId}`);
        return response.data;
    },

    generate: async (tourId: string, options: GenerateNarrationOptions = {}) => {
        const response = await api.post<{ generated: number; skipped: number; narrations: TourNarration[] }>(
            `/tours/${tourId}/narrations/generate`,
            options
        );
        return response.data;
    },

    generateTts: async (tourId: string, options: GenerateTtsOptions = {}) => {
        const response = await api.post<{ generated: number; narrations: TourNarration[] }>(
            `/tours/${tourId}/narrations/generate-tts`,
            options
        );
        return response.data;
    },

    generateSingleTts: async (tourId: string, narrationId: string) => {
        const response = await api.post<TourNarration>(
            `/tours/${tourId}/narrations/${narrationId}/tts`,
            { languages: ['VI', 'EN'] }
        );
        return response.data;
    }
};
