import { fireEvent, render, within } from '@testing-library/react';
import { beforeEach, describe, expect, it, vi } from 'vitest';

import LocalizationPanel from '../LocalizationPanel';
import { clearAllPendingTranslationRequests, markTranslationRequestPending } from '../../../services/localizationPendingRequests';

const emitAction = vi.fn();
const emitDropdownView = vi.fn();
const emitPendingState = vi.fn();

const usePoiLocalizationsMock = vi.fn();
const useSupportedLanguagesMock = vi.fn();

vi.mock('@localization-shared', async () => {
  const actual = await vi.importActual<any>('@localization-shared');
  return {
    ...actual,
    usePoiLocalizations: (...args: unknown[]) => usePoiLocalizationsMock(...args),
  };
});

vi.mock('../../../hooks/useSupportedLanguages', () => ({
  useSupportedLanguages: (...args: unknown[]) => useSupportedLanguagesMock(...args),
}));

vi.mock('../../../services/localization-analytics', () => ({
  localizationAnalytics: {
    emitAction: (...args: unknown[]) => emitAction(...args),
    emitDropdownView: (...args: unknown[]) => emitDropdownView(...args),
    emitPendingState: (...args: unknown[]) => emitPendingState(...args),
  },
}));

const supportedLanguages = [
  {
    code: 'VI',
    label: 'Vietnamese',
    flag: '🇻🇳',
    enabled: true,
    supportsText: true,
    supportsTts: true,
    priority: 1,
    shopOwnerEditable: true,
    defaultVoice: 'vi-VN',
    updatedAt: '2026-04-02T00:00:00.000Z',
  },
  {
    code: 'EN',
    label: 'English',
    flag: '🇬🇧',
    enabled: true,
    supportsText: true,
    supportsTts: true,
    priority: 2,
    shopOwnerEditable: false,
    defaultVoice: 'en-US',
    updatedAt: '2026-04-02T00:00:00.000Z',
  },
  {
    code: 'FR',
    label: 'French',
    flag: '🇫🇷',
    enabled: true,
    supportsText: true,
    supportsTts: false,
    priority: 3,
    shopOwnerEditable: false,
    updatedAt: '2026-04-02T00:00:00.000Z',
  },
  {
    code: 'DE',
    label: 'German',
    flag: '🇩🇪',
    enabled: false,
    supportsText: true,
    supportsTts: false,
    priority: 4,
    shopOwnerEditable: false,
    updatedAt: '2026-04-02T00:00:00.000Z',
  },
] as const;

function setupMockHooks() {
  useSupportedLanguagesMock.mockReturnValue({
    languages: supportedLanguages,
    isLoading: false,
    refetch: vi.fn(),
    isCatalogStale: () => false,
  });

  usePoiLocalizationsMock.mockReturnValue({
    isLoading: false,
    isSaving: false,
    data: {
      poiId: 'poi-1',
      meta: { lastSyncedAt: '2026-04-02T00:00:00.000Z' },
      items: [
        {
          language: 'VI',
          name: 'Tên tiếng Việt',
          description: 'Mô tả tiếng Việt',
          autoGenerated: false,
          updatedAt: '2026-04-02T00:00:00.000Z',
          updatedBy: 'admin',
        },
        {
          language: 'EN',
          name: 'English Name',
          description: 'English Description',
          autoGenerated: false,
          updatedAt: '2026-04-02T00:00:00.000Z',
          updatedBy: 'admin',
        },
      ],
    },
    state: {
      items: [
        {
          language: 'VI',
          name: 'Tên tiếng Việt',
          description: 'Mô tả tiếng Việt',
          autoGenerated: false,
          updatedAt: '2026-04-02T00:00:00.000Z',
          updatedBy: 'admin',
        },
        {
          language: 'EN',
          name: 'English Name',
          description: 'English Description',
          autoGenerated: false,
          updatedAt: '2026-04-02T00:00:00.000Z',
          updatedBy: 'admin',
        },
      ],
      draftByLanguage: {},
      dirtyMap: {},
      errors: {},
      pendingMutation: null,
      lastSyncedAt: '2026-04-02T00:00:00.000Z',
      lastFetchedAt: '2026-04-02T00:00:00.000Z',
    },
    editLanguage: vi.fn(),
    discardLanguage: vi.fn(),
    saveLanguage: vi.fn().mockResolvedValue(undefined),
    deleteLanguage: vi.fn().mockResolvedValue(undefined),
    refetch: vi.fn().mockResolvedValue(undefined),
  });
}

describe('LocalizationPanel shop-owner flow', () => {
  beforeEach(() => {
    localStorage.clear();
    clearAllPendingTranslationRequests();
    emitAction.mockClear();
    emitDropdownView.mockClear();
    emitPendingState.mockClear();
    usePoiLocalizationsMock.mockReset();
    useSupportedLanguagesMock.mockReset();
    setupMockHooks();
  });

  it('hides disabled languages and renders existing translations readonly', () => {
    const { container } = render(
      <LocalizationPanel
        poiId="poi-1"
        baseLanguage={'VI' as never}
        role="shopOwner"
      />
    );
    const panel = within(container);

    expect(panel.queryByText('German')).not.toBeInTheDocument();
    expect(panel.getByText('English')).toBeInTheDocument();

    fireEvent.click(panel.getByRole('button', { name: /English/i }));

    expect(panel.getByDisplayValue('English Name')).toBeDisabled();
    expect(panel.getByDisplayValue('English Description')).toBeDisabled();
    expect(panel.queryByRole('button', { name: /Save/i })).not.toBeInTheDocument();
    expect(panel.queryByRole('button', { name: /Delete/i })).not.toBeInTheDocument();
  });

  it('shows request translation for missing languages and persists pending locally', () => {
    const { container } = render(
      <LocalizationPanel
        poiId="poi-1"
        baseLanguage={'VI' as never}
        role="shopOwner"
      />
    );
    const panel = within(container);

    fireEvent.click(panel.getByRole('button', { name: /French/i }));

    const requestButton = panel.getByRole('button', { name: /Request translation/i });
    expect(requestButton).toBeEnabled();

    fireEvent.click(requestButton);

    expect(emitAction).toHaveBeenCalledWith(
      expect.objectContaining({
        action: 'request_translation',
        poiId: 'poi-1',
        role: 'shopOwner',
        success: true,
      })
    );
    expect(panel.getByRole('button', { name: /Request translation/i })).toBeDisabled();
    expect(panel.getByText('Pending')).toBeInTheDocument();
    expect(panel.getByText('Yêu cầu đang chờ admin xử lý.')).toBeInTheDocument();
  });

  it('keeps pending request disabled after reopening the panel', () => {
    markTranslationRequestPending('poi-1', 'FR');

    const { container } = render(
      <LocalizationPanel
        poiId="poi-1"
        baseLanguage={'VI' as never}
        role="shopOwner"
      />
    );
    const panel = within(container);

    fireEvent.click(panel.getByRole('button', { name: /French/i }));

    const requestButton = panel.getByRole('button', { name: /Request translation/i });
    expect(requestButton).toBeDisabled();
    expect(panel.getByText('Pending')).toBeInTheDocument();
  });
});
