-- CreateEnum
CREATE TYPE "NarrationType" AS ENUM ('INTRO', 'TRANSITION', 'ARRIVAL', 'OUTRO');

-- AlterTable
ALTER TABLE "tour_pois" ALTER COLUMN "updatedAt" DROP DEFAULT;

-- CreateTable
CREATE TABLE "tour_narrations" (
    "id" TEXT NOT NULL,
    "tourId" TEXT NOT NULL,
    "type" "NarrationType" NOT NULL,
    "orderIndex" INTEGER NOT NULL,
    "fromPoiId" TEXT,
    "toPoiId" TEXT,
    "scriptVi" TEXT,
    "scriptEn" TEXT,
    "audioViUrl" TEXT,
    "audioEnUrl" TEXT,
    "isAutoGenerated" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "tour_narrations_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE INDEX "tour_narrations_tourId_idx" ON "tour_narrations"("tourId");

-- CreateIndex
CREATE UNIQUE INDEX "tour_narrations_tourId_type_orderIndex_key" ON "tour_narrations"("tourId", "type", "orderIndex");

-- AddForeignKey
ALTER TABLE "tour_narrations" ADD CONSTRAINT "tour_narrations_tourId_fkey" FOREIGN KEY ("tourId") REFERENCES "tours"("id") ON DELETE CASCADE ON UPDATE CASCADE;
